# -*- coding: utf-8 -*-
"""appspam.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OrstA2Bz2Lr7q00FpXqz8Sjf22jsibtV
"""

import streamlit as st
import joblib
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

nltk.download('punkt')
nltk.download('stopwords')

ps = PorterStemmer()

def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Tokenize
    words = nltk.word_tokenize(text)
    # Remove non-alphanumeric tokens and stopwords, then stem
    processed_words = [ps.stem(word) for word in words if word.isalnum() and word not in stopwords.words('english')]
    return " ".join(processed_words)

# Load the TF-IDF vectorizer and trained model
vectorizer = joblib.load('tfidf_vectorizer.joblib')  # Corrected the path
model = joblib.load('mb_model.joblib')  # Corrected the path

st.title("Email Spam Classifier")
st.write("Enter the email content below to classify it as Spam or Not Spam.")

# Text area for email input
email_input = st.text_area("Email Content", height=150)

if st.button('Classify'):
    if email_input:
        # Preprocess the input
        processed_email = preprocess_text(email_input)
        # Vectorize the input
        vectorized_email = vectorizer.transform([processed_email])
        # Predict using the loaded model
        prediction = model.predict(vectorized_email)[0]
        # Display the result
        if prediction == 1:
            st.error("This email is classified as Spam.")
        else:
            st.success("This email is classified as Not Spam.")
    else:
        st.warning("Please enter the email content to classify.")
